import type { Province } from '../types/game';
import { STARTER_WORLD_ID } from '../constants';

export const STARTER_PROVINCES: Province[] = [
  {
    id: 'north-fen',
    mapId: STARTER_WORLD_ID,
    name: 'North Fen',
    shapeKey: 'north-fen',
    centroidX: 90,
    centroidY: 75,
    terrainType: 'plains',
    isProductionCenter: false,
    buildableUnitTypes: [],
    baseYield: { food: 4 },
  },
  {
    id: 'riverbend',
    mapId: STARTER_WORLD_ID,
    name: 'Riverbend',
    shapeKey: 'riverbend',
    centroidX: 240,
    centroidY: 75,
    terrainType: 'urban',
    isProductionCenter: true,
    buildableUnitTypes: ['infantry', 'artillery'],
    baseYield: { food: 5 },
  },
  {
    id: 'duskfield',
    mapId: STARTER_WORLD_ID,
    name: 'Duskfield',
    shapeKey: 'duskfield',
    centroidX: 400,
    centroidY: 75,
    terrainType: 'plains',
    isProductionCenter: false,
    buildableUnitTypes: [],
    baseYield: { food: 4 },
  },
  {
    id: 'blackharbor',
    mapId: STARTER_WORLD_ID,
    name: 'Blackharbor',
    shapeKey: 'blackharbor',
    centroidX: 550,
    centroidY: 75,
    terrainType: 'urban',
    isProductionCenter: false,
    buildableUnitTypes: [],
    baseYield: { metal: 4 },
  },
  {
    id: 'ironcrest',
    mapId: STARTER_WORLD_ID,
    name: 'Ironcrest',
    shapeKey: 'ironcrest',
    centroidX: 90,
    centroidY: 205,
    terrainType: 'hills',
    isProductionCenter: false,
    buildableUnitTypes: [],
    baseYield: { metal: 4 },
  },
  {
    id: 'stonegate',
    mapId: STARTER_WORLD_ID,
    name: 'Stonegate',
    shapeKey: 'stonegate',
    centroidX: 240,
    centroidY: 205,
    terrainType: 'urban',
    isProductionCenter: true,
    buildableUnitTypes: ['infantry', 'artillery', 'armor'],
    baseYield: { fuel: 3 },
  },
  {
    id: 'emberplain',
    mapId: STARTER_WORLD_ID,
    name: 'Emberplain',
    shapeKey: 'emberplain',
    centroidX: 400,
    centroidY: 205,
    terrainType: 'urban',
    isProductionCenter: true,
    buildableUnitTypes: ['infantry', 'artillery', 'armor'],
    baseYield: { fuel: 3 },
  },
  {
    id: 'northhold',
    mapId: STARTER_WORLD_ID,
    name: 'Northhold',
    shapeKey: 'northhold',
    centroidX: 550,
    centroidY: 205,
    terrainType: 'urban',
    isProductionCenter: true,
    buildableUnitTypes: ['infantry', 'artillery'],
    baseYield: { food: 5 },
  },
  {
    id: 'mossplain',
    mapId: STARTER_WORLD_ID,
    name: 'Mossplain',
    shapeKey: 'mossplain',
    centroidX: 90,
    centroidY: 345,
    terrainType: 'plains',
    isProductionCenter: false,
    buildableUnitTypes: [],
    baseYield: { food: 4 },
  },
  {
    id: 'cold-quarry',
    mapId: STARTER_WORLD_ID,
    name: 'Cold Quarry',
    shapeKey: 'cold-quarry',
    centroidX: 240,
    centroidY: 345,
    terrainType: 'hills',
    isProductionCenter: false,
    buildableUnitTypes: [],
    baseYield: { metal: 4 },
  },
  {
    id: 'red-mesa',
    mapId: STARTER_WORLD_ID,
    name: 'Red Mesa',
    shapeKey: 'red-mesa',
    centroidX: 400,
    centroidY: 345,
    terrainType: 'hills',
    isProductionCenter: false,
    buildableUnitTypes: [],
    baseYield: { metal: 4 },
  },
  {
    id: 'sunport',
    mapId: STARTER_WORLD_ID,
    name: 'Sunport',
    shapeKey: 'sunport',
    centroidX: 550,
    centroidY: 345,
    terrainType: 'plains',
    isProductionCenter: false,
    buildableUnitTypes: [],
    baseYield: { food: 4 },
  },
];
