import type { ProvinceEdge } from '../types/game';

const starterUndirectedEdges = [
  ['north-fen', 'riverbend'],
  ['riverbend', 'duskfield'],
  ['duskfield', 'blackharbor'],
  ['ironcrest', 'stonegate'],
  ['stonegate', 'emberplain'],
  ['emberplain', 'northhold'],
  ['mossplain', 'cold-quarry'],
  ['cold-quarry', 'red-mesa'],
  ['red-mesa', 'sunport'],
  ['north-fen', 'ironcrest'],
  ['ironcrest', 'mossplain'],
  ['riverbend', 'stonegate'],
  ['stonegate', 'cold-quarry'],
  ['duskfield', 'emberplain'],
  ['emberplain', 'red-mesa'],
  ['blackharbor', 'northhold'],
  ['northhold', 'sunport'],
] as const;

const us48UndirectedEdges = [
  ['us-al', 'us-fl'],
  ['us-al', 'us-ga'],
  ['us-al', 'us-ms'],
  ['us-al', 'us-tn'],
  ['us-ar', 'us-la'],
  ['us-ar', 'us-mo'],
  ['us-ar', 'us-ms'],
  ['us-ar', 'us-ok'],
  ['us-ar', 'us-tn'],
  ['us-ar', 'us-tx'],
  ['us-az', 'us-ca'],
  ['us-az', 'us-nm'],
  ['us-az', 'us-nv'],
  ['us-az', 'us-ut'],
  ['us-ca', 'us-nv'],
  ['us-ca', 'us-or'],
  ['us-co', 'us-ks'],
  ['us-co', 'us-ne'],
  ['us-co', 'us-nm'],
  ['us-co', 'us-ut'],
  ['us-co', 'us-wy'],
  ['us-ct', 'us-ma'],
  ['us-ct', 'us-ny'],
  ['us-ct', 'us-ri'],
  ['us-de', 'us-md'],
  ['us-de', 'us-pa'],
  ['us-fl', 'us-ga'],
  ['us-ga', 'us-nc'],
  ['us-ga', 'us-sc'],
  ['us-ga', 'us-tn'],
  ['us-ia', 'us-il'],
  ['us-ia', 'us-mn'],
  ['us-ia', 'us-mo'],
  ['us-ia', 'us-ne'],
  ['us-ia', 'us-sd'],
  ['us-ia', 'us-wi'],
  ['us-id', 'us-mt'],
  ['us-id', 'us-nv'],
  ['us-id', 'us-or'],
  ['us-id', 'us-ut'],
  ['us-id', 'us-wa'],
  ['us-id', 'us-wy'],
  ['us-il', 'us-in'],
  ['us-il', 'us-ky'],
  ['us-il', 'us-mo'],
  ['us-il', 'us-wi'],
  ['us-in', 'us-ky'],
  ['us-in', 'us-mi'],
  ['us-in', 'us-oh'],
  ['us-ks', 'us-mo'],
  ['us-ks', 'us-ne'],
  ['us-ks', 'us-ok'],
  ['us-ky', 'us-mo'],
  ['us-ky', 'us-oh'],
  ['us-ky', 'us-tn'],
  ['us-ky', 'us-va'],
  ['us-ky', 'us-wv'],
  ['us-la', 'us-ms'],
  ['us-la', 'us-tx'],
  ['us-ma', 'us-nh'],
  ['us-ma', 'us-ny'],
  ['us-ma', 'us-ri'],
  ['us-ma', 'us-vt'],
  ['us-md', 'us-pa'],
  ['us-md', 'us-va'],
  ['us-md', 'us-wv'],
  ['us-me', 'us-nh'],
  ['us-mi', 'us-oh'],
  ['us-mi', 'us-wi'],
  ['us-mn', 'us-nd'],
  ['us-mn', 'us-sd'],
  ['us-mn', 'us-wi'],
  ['us-mo', 'us-ne'],
  ['us-mo', 'us-ok'],
  ['us-mo', 'us-tn'],
  ['us-ms', 'us-tn'],
  ['us-mt', 'us-nd'],
  ['us-mt', 'us-sd'],
  ['us-mt', 'us-wy'],
  ['us-nc', 'us-sc'],
  ['us-nc', 'us-tn'],
  ['us-nc', 'us-va'],
  ['us-nd', 'us-sd'],
  ['us-ne', 'us-sd'],
  ['us-ne', 'us-wy'],
  ['us-nh', 'us-vt'],
  ['us-nm', 'us-ok'],
  ['us-nm', 'us-tx'],
  ['us-nv', 'us-or'],
  ['us-nv', 'us-ut'],
  ['us-ny', 'us-pa'],
  ['us-ny', 'us-vt'],
  ['us-oh', 'us-pa'],
  ['us-oh', 'us-wv'],
  ['us-ok', 'us-tx'],
  ['us-or', 'us-wa'],
  ['us-pa', 'us-wv'],
  ['us-sd', 'us-wy'],
  ['us-tn', 'us-va'],
  ['us-ut', 'us-wy'],
  ['us-va', 'us-wv'],
] as const;

function toDirectedEdges(undirectedEdges: readonly (readonly [string, string])[]): ProvinceEdge[] {
  return undirectedEdges.flatMap(([fromProvinceId, toProvinceId]) => [
    { fromProvinceId, toProvinceId, distance: 1 },
    { fromProvinceId: toProvinceId, toProvinceId: fromProvinceId, distance: 1 },
  ]);
}

export const STARTER_PROVINCE_EDGES: ProvinceEdge[] = toDirectedEdges(
  starterUndirectedEdges,
);

export const US48_V1_PROVINCE_EDGES: ProvinceEdge[] = toDirectedEdges(
  us48UndirectedEdges,
);

export const PROVINCE_EDGES: ProvinceEdge[] = [
  ...STARTER_PROVINCE_EDGES,
  ...US48_V1_PROVINCE_EDGES,
];
